### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by krstljrk** [krstljrk/react-to-do#1]
- [x] Create To Do item component
- [x] Create Store
- [x] Connect Store to Component
- [x] Replace old Redux with reduxjs/toolkit tools
- [x] Display To Do Item
- [x] Add "Delete" button and functionality 
- [x] Add button to mark task as 'Complete'
- [ ] Add "Edit" button and functionality **WIP**
- [ ] Add "Complete" functionality
- [ ] Allow sorting of To Do items by 'To Do', 'Done', 'All'
- [ ] Add CSS
- [ ] Enable key 'Enter' to adding new todos

**Comment by krstljrk** [comment]
https://github.com/krstljrk/react-to-do/issues/2
